Port standardization
dappnode/DAppNodePackage-gnosis-beacon-chain-prysm pull request #35
Opened 2022-07-01 14:01 UTC by tropicar

According to this issue https://github.com/dappnode/DAppNode/issues/457
We are selecting the host port for the client.

In prysm client you can change these default ports using these flags:
```
   --p2p-tcp-port value            The port used by libp2p. (default: 13000)
   --p2p-udp-port value            The port used by discv5. (default: 12000)
```

2022-07-08 11:49 UTC, tropicar commented
> there are up to three possible prysm packages (prater eth2 and gnosis chain). How do we handle this situation if the three packages want to use the same hot port?

The port is defined in the next way; chainID multiplied by 10 + default port + clientID(this number is defined by us). You can read the specific feature here https://github.com/dappnode/DAppNode/issues/457

For that specific case:
Prysm: TCP/13103 & UDP/12103
Prysm Prater:  TCP/13503 & UDP/12503
Prysm Gnosis: TCP/14003 & UDP/13003
With the chainID we avoid the collision in the same clients with different networks
Multiply by ten because because of the testnets has the same client and chainIDs have similar values (and how they use the same client, clientID and deffault port are the same ).

2022-09-10 02:47 UTC, alexpeterson91 commented on docker-compose.yml
> +      - "13004:13004/tcp"
```suggestion
      - "14003:14003/tcp"
```
This is the specified port in the port standardization.

2022-09-10 02:51 UTC, alexpeterson91 requested changes
not the right ports according to the spec you defined

2022-09-10 02:51 UTC, alexpeterson91 commented on docker-compose.yml
> +      - "12004:12004/udp"
```suggestion
      - "13003:13003/udp"
```
this is the specified port.

2022-09-10 02:51 UTC, alexpeterson91 commented on docker-compose.yml
> +      P2P_TCP_PORT: 13004
```suggestion
      P2P_TCP_PORT: 14003
```

2022-09-10 02:51 UTC, alexpeterson91 commented on docker-compose.yml
> +      P2P_UDP_PORT: 12004
```suggestion
      P2P_UDP_PORT: 13004
```

2022-10-19 07:23 UTC, alexpeterson91 approved these changes

2022-10-19 07:26 UTC, alexpeterson91 approved these changes

2022-10-19 07:26 UTC, merged